version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: food-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: food_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: food-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/food_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: bjidnswdjfndjdsjvjdshjjffnididiowdjqiejijeedjjjnjqdnjenjesdfg
    ports:
      - "8080:8080"
    volumes:
      - uploads:/uploads

volumes:
  pgdata:
  uploads:
